### PR TITLE
General Tree and Sap Overhaul

### PR DESCRIPTION
**Pull request by malcolmriley**
What started out as a simple idea rapidly ballooned into total ecosystem overhaul, for reasons that will be explained further. Everything was quite tangled, and hopefully this is a step towards partitioning out interesting bits of logic and increasing flexibility as well as paving the way to making Tree play a bit more interesting!

**OVERVIEW OF CHANGES**
- Implements and integrates `BranchProvider` component system. Encapsulates and provides for specialized, branch-specific logic on branch placement; furthermore provides the `TreeController` with the capability of placing the branches that it provides.
- Overhauls `TreeController` to utilize the new `BranchProvider` system. Externalizes placement logic, and basically makes it the `BranchProvider`s job to handle placement and checking.
- Overhauls sap prefabs to use new `BranchProvider` system. Sap now has the enum property `SapType` that can be used to selectively add sap to individual `BranchProvider` reserves.
- Nondestructively implements and integrates new `UIBranchElement` and associated parts. With the modern `BranchProvider` system, the UI element needs more flexibility (since there isn't necessarily a fixed four types of branch placement anymore).
- Namespace `RiseExtensions` now includes some small but nifty utilities and conveniences.

**BRANCHPROVIDER IMPLEMENTATION**
- The abstract class `BranchProvider` contains a number of fields and methods related to the placement of branches. These methods and fields are called/queried at appropriate times by the `TreeController` - more on that later. Most importantly, each `BranchProvider` features a `GetBranch()` method - this is the core functionality. Overriding this method allows different branches to be returned under different conditions if necessary. Also, each `BranchProvider` individually tracks a sap pool, minimum and maximum sap values, `Sprite` references to be used for the UI components, and `AudioClip` references that are played for growth and so forth. This permits highly individualized and customizable behaviors _per branch type_.
- By attaching `BranchProvider` inheritors to a component with a `TreeController`, the `TreeController` gains the capability to place whatever branch is provided by it.
- Extending the `BranchProvider` class permits very flexible placement logic moving forward. For instance, extending `BranchProvider` and overriding `OnBranchPlaced()` allows specialized responses to the placement of a branch - Other game objects could be spawned or removed, for instance, or some other environmental condition set, or really anything at all that needs to be done. The reference implementations `BranchProviderSimple` and `BranchProviderRandom` are provided.
- `BranchProviderSimple` maintains a single reference to a branch prefab, returning that reference when it comes time to instantiate the branch in `TreeController`. Furthermore, it is sap-type sensitive; meaning that the sap quantity is only modified when the appropriate type of sap is collected. Yes, that is the same behavior as before, but consider this: extending this method allows the `BranchProvider` to respond to multiple types of sap, or all sap, or a super-special "wild-card" sap... the options here are basically limitless.
- `BranchProviderRandom` is like `BranchProviderSimple`, but it maintains a list of branch prefab references and returns one of them at random when `GetBranch()` is called. Here we see the use of overriding `GetBranch()` to easily provide an interesting behavior.

**TREECONTROLLER OVERHAUL**
- Much of the logic related to branch placement has been externalized; all of the interesting bits have been relocated into `BranchProvider`.
- Instead of a fixed array of branch prefabs to be placed, the `TreeController` scans for attached `BranchProvider` components, and uses these for placement logic. Basically, if a `BranchProvider` is attached, the `TreeController` gains use of it; scrolling and selection between branch types is handled automatically. These `BranchProvider` components can be attached and detached or enabled and disabled at runtime, and the system _should_ be able to account for it (I'm sure there are some edge cases I didn't think of) but if you do this, call `UpdateComponents()` on the `TreeController` to re-establish all references and ensure that they're sorted in the right order (since this is the order that you scroll through them in).
- Otherwise, the `TreeController` works very much the same as before. It parses tree player input, moves the reticle around, and at the correct time, tries to place and break branches.
- **Important:** The UI delegate events have been marked as deprecated and should ultimately be removed.

**SAP PREFAB CHANGES**
- `SapType` is now `SapBehavior`, and has slightly more capabilities.
- `SapBehavior` now adjusts the size of the model based on the amount of sap it contains.
- `SapBehavior` features a `OnSapCollected()` method that is called when it is picked up - or, I suppose, whenever the programmer feels like. This is probably a good spot to put pickup particle effects and the like. I have relocated the sap collection size tween here.
- `SapBehavior` now has a `SapType` field. Use this for "communicating" with the `BranchProvider`; for instance, certain `BranchProvider`s could be less choosy about the sap type required for pick up, or we could add more sap types, or whatever strikes our fancy.

**BRANCH UI CHANGES**
- There is now the `UIBranchElement` prefab and associated script `UIBranchManager`.
- The `UIBranchManager` maintains a reference to a `TreeController`, a branch `Image`, and any number of leaf `Image`s. These Images are not necessarily on the same component as the `UIBranchManager`.
- When the `OnUpdateElement()` callback is called, the `UIBranchManager` automatically instructs the `Image` references to use the branch and leaf `Sprite`s provided by the `BranchProvider`. Furthermore, it automatically enables and disables leaves as necessary to reflect the appropriate sap count.
- This means we can have one `UIBranchElement` on the canvas instead of four specific ones. Alternatively, we can have a different `UIBranchElement` for different scenes, or whatever we please.
- This also means that the `UIBranchElement` supports an arbitrary number of leaves without requiring any code changes. Just add more `Image` children to the prefab and add their references to the list.
- Finally, since the `UIBranchElement` receives its sprites from the `BranchProvider`, any new `BranchProvider` types will be automatically supported by the new UI without any changes.
- **Caveat:** The winter branch type uses icicles instead of leaves. This is the only branch that has its elements in different positions. To address this, the simple solution would be to swap out the icicle sprite for something else (winter berries maybe, since trees don't really "grow" icicles "from sap" like they do flowers and leaves). Alternatively, as stated above, a second `UIBranchElement` prefab with adjusted `Image` positions can be used. In either case, no code changes will be necessary.
- **Important:** I haven't removed the old UI system. All the old prefabs are still there, even though they're not terribly functional under the new system.

**RISEEXTENSIONS EXTENSIONS**
- Implements some static utilities in `Shared > Utilities.cs` for the namespace `RiseExtensions`.
- Tags: Instead of putting a bunch of string literals everywhere, we can put them here and refer to them by `Tags.NAME` wherever `RiseExtensions` is used. That way if we change one tag, we don't have to hunt down every last string literal.
- SapTypes: This is the new home of the `SapType` enum. It just made sense.
- `GameMode`: I saw hints of a string-literal backed game mode value... let's not do that, and instead use enums. More robust, in my opinion, and not prone to typos.
- `Clamp` and `CheckEpsilon` extension methods for `IComparable<>` and floating-point types, respectively. Now, wherever we use `RiseExtensions` we can call one of those methods on the thingamabob at hand to perform its functionality. Yes, this even means for so-called "primitive types": To clamp `float zoop` between 0.5 and 3.5, you can just do `float clampedZoop = zoop.Clamp(0.5F, 3.5F)`. You can even do ugly things like `(zoop + doop).Clamp(40, 999)` or whatever strikes your fancy.
- This is probably a good place to put various static utility or extension methods we want to use more than once. Code is meant to be reused.

**Example BranchProvider inheritor Capabilities:**
- Override `UpdateSap()` to change how the `BranchProvider` responds to a requested change in sap value based on the detected `SapType`. Perhaps there is a "full refill" sap, or a trick sap that depletes your reserve, or a wildcard sap that is accepted by all `BranchProvider`s.
- Override `CheckSap()` to change how the `BranchProvider` checks to see whether there's enough sap in the reserve. Perhaps there is a shared external reserve for some other purpose, or a special branch type that can be placed infinitely.
- Override `PlaceBranch()` to change what happens when the `TreeController` attempts to place a branch - perhaps a new enemy is spawned, or a different branch is automatically removed, etc.
- Override `CanPlaceBranch()` to implement custom checking logic for whether a branch is allowed to be placed - Perhaps there is a branch type that can only be placed on a specific surface, or at a specific distance from another thing, or if another branch has been placed already (for a tightrope vine between two, for instance).
- Override `OnBranchPlaced()` to make something happen when the branch is placed successfully. Perhaps a particle effect fires, or a tween happens, or the squirrel does a happy dance animation.

Whew, that was a lot... Sorry for writing a novel. Point is, the new system opens up a lot of possibilities and makes these kinds of changes much easier to do.

_**IMPORTANT IMPORTANT IMPORTANT**_
This branch has acquired `fix_msr_misc` - I needed to use some of the fixes in there. Approving this PR implicitly approves `fix_msr_misc`; base at 0376b33.

### CODE REVIEW

**Comment by malcolmriley** [comment]
Putting another comment way down here near the approve button:

This branch has acquired `fix_msr_misc`, please review that one before reviewing/merging this one.

**Comment by malcolmriley** [comment]
Unfortunately there isn't really a good way to extricate the old system without disabling it wholesale (since `UIController` is monolithic and enables the old prefabs on run). I've disabled the whole system entirely in 2e742a1 to make reviewing easier, but this does break the other UI components.

2e742a1 can be safely reverted if desired, but all it does is disable (not remove) `UIController` and the other branch UI prefabs.

The best demonstration of the new UI model is found by looking at the new `UIBranchElement` object in the Canvas - observe that there is one and not four UI elements (more maintainable), and that it automatically supports new `BranchProvider` types without code changes since `BranchProvider` also supplies the `Sprite` that it draws (more flexible).

**Comment by malcolmriley** [comment]
I'd also like to say that I didn't feel comfortable mucking around in `UIController` too much because that was beyond the scope of my task and I felt that my changes were intrusive enough without overhauling yet another system.

**Comment by NicolaeChristof** [comment]
This all sounds amazing! It sparked a bunch of cool ideas as I was reading through the changes. I would like to see how this all fits together with our UI (but I assume you intended for Aadam to incorporate that). I will look more closely though the code when I get some free time. Thank you very much for all this hard work!

**Comment by malcolmriley** [comment]
It's not that I intended Aadam to do more work, it's that the existing UI branch system didn't work with the new `TreeController` system because it was designed with the old one in mind - it assumed that there was a fixed array of branch types, for instance, and that `TreeController` managed the sap reserve; neither of which are true anymore.

The only UI changes that this PR makes is to the branch UI component - if those parts are removed from `UIController`, then `UIController` can be safely re-enabled. I didn't want to remove those parts myself because, like I said, this overhaul is intrusive enough already, and nobody asked me to stick my grubby mitts there.

**Comment by malcolmriley** [comment]
Since there seems to be some confusion about the UI changes, I'll discuss them here in more detail:

**Old Branch UI System**
- Four branch UI objects managed by the `UIController`, one for each branch type.
- These branch UI objects are basically component containers only; they hold images and little else.
- The `UIController` selectively enables and disables these UI objects as needed based on information it queries from `TreeController`
- The `UIController` is designed based on a few assumptions: namely, that there is a fixed number of branch types; that the `TreeController` manages both sap reserves and an array reference to the branch types it can place, and that the sprites for drawing each UI element will never change. These assumptions are no longer true, so a new branch UI system was needed.

**New Branch UI System**
- **Problem:** Since the tree player doesn't necessarily always have the ability to place exactly four branch types (could be more or less now), the new UI system needs to account for that.
- **Solution: ** New UI element is generic and while it maintains references to `Image` components on its children, the actual `Sprite` that the `Image` draws isn't fixed.
- Now, `TreeController` calls `OnUpdateElement()` as a callback when it detects that the player has switched to a new branch type, and the `UIBranchManager` responds to the change using the supplied `BranchProvider` parameter. _Currently_ all it does is ask the supplied `BranchProvider` what new `Sprite`s it should use for drawing the branch, and then enables/disables a proportion of its managed leaf `Image`s based on the amount of sap the `BranchProvider` says it has over the total amount of sap the `BranchProvider` can contain. Importantly, all of this logic can be overridden and treated separately - you can override `OnUpdateElement()` to draw the stuff differently for different branches, or whatever.
- This means that the new `UIBranchElement` automatically supports any new `BranchProvider` that is added to the `TreeController` _without any needed changes to the UI_.
- This also means that the amount of leaves can be very easily changed. Just add another `Image` somewhere (literally anywhere on the canvas), and inform `UIBranchManager` about it by dragging the object to the `Leaves` field in the Inspector. `UIBranchManager` will treat that `Image` as a leaf and enable/disable it depending on the proportion of sap the selected branch has. To reduce the number of leaves, just remove it from the list. In short, this change decouples the maximum sap reserve from the exact quantity of leaves on the UI. We are now free to do silly things like give decimal quantities of sap or have different minimum and maximum sap quantities per branch type, and the `UIBranchManager` will handle it without complaint.

To be perfectly clear: the only UI changes in this PR are to:
- Add a new UIBranchElement prefab to the Canvas to display the branches and leaves as needed
- Disable (not remove) `UIController` and the old four-object Canvas elements (since they don't "play nice" with the new system as Barbara observed).

The other UI things in `UIController` still work, I haven't broken those AFAIK.

**Pull request merged**
