### PR TITLE
Enhancement controller remap

### PR DESCRIPTION
**Pull request by NicolaeChristof**
Enhanced player control mapping that no longer uses triggers and bumpers (much cleaner I think)

New layout:
Squirrel is the same

Tree:
A to place
B to delete
X to swap between players in single player
Y to swap branch types

And I threw some nice grass into our scene

### CODE REVIEW

**Comment by NicolaeChristof** [comment]
I agree it takes a bit of getting used to but I think it will be more intuitive to players who are not use to using a controller

**Comment by NicolaeChristof** [comment]
Hey Malcolm, I can tell you are really frustrated. I realize now that the work I did in this PR could have utilized your InputHelper and didn't and I can see how that would make you feel like we are all ignoring your work. This was not my intention at all and I am very sorry for making you feel like your work has gone unnoticed. I promise you it hasn't, I have been extremely happy with your progress. You come up with ideas for making our game better that I never could have come up with myself and that's part of why you are such a valuable member of our team. I am truly sorry, I definitely let you down on this one. I will rewrite this PR in a way that utilizes the InputHelper.

And as far as the playercontroller rework, I assigned that task to you because I felt like you would be the best suited for the task. I promise that work won't be undervalued. I hope this helps you feel a bit better, Ill try to be more aware of the code I write going forward

**Comment by NicolaeChristof** [comment]
I'm having a bit of trouble with the rebinding aspect of the inputhelper. You can look at my attempt at in on line 56-79 of the SettingsController file. But other than that the InputHelper is now fully integrated into our systems. Its much cleaner than what we had before so thank you Malcolm for taking the time to do this.

**Comment by malcolmriley** [comment]
You were doing everything correctly, but the `InputHelper` wouldn't have been able to work with that locally-scoped `ControlProfile` instance instantiated in the `SettingsController`.

This is perhaps a weakness of the `InputHelper's` design, but it is only aware of the two `ControlProfile` instances it directly controls, `PlayerOne` and `PlayerTwo`. This is because (as far as I am aware) we only ever intended to support two players overall; thus I worked under the assumption that at most two `ControlProfile` instances would be needed at any given time.

To circumvent this shortcoming I have made the following changes to this branch:
- I moved your rebinding work in `SettingsController` to a new `SetKeyboard` convenience method in `InputHelper`; this method is called on the `PlayerOne` instance in `SettingsController` under the appropriate circumstances.
- I moved all of the InputHelper necessaries into their own namespace, `RiseExtensions`. This will hopefully cut down on typing; instead of putting `InputHelper.SquirrelInput.YaddaYadda` everywhere, we need only put a `using` directive at the top of the file to gain use of it.
- I removed all stale `InputHelper` components from the `Master Controller` instances in each scene (These objects should perhaps be prefabs?) - Now that `InputHelper` is static, we don't need to put those components everywhere. The original idea was to attach an `InputHelper` instance on the `Master Controller`, and then in `RiseBehavior` establish a reference to it (granting everybody an `_input` field), but I agree with your decision to make it static, seems more convenient.

I believe these changes rectify the last of the outstanding issues with this PR.

It wasn't designed to handle keyboard inputs, so I'm pleasantly surprised to see that it works at all. Nicely done!

**Pull request merged**
