### PR TITLE
Feature new assets

### PR DESCRIPTION
**Pull request by NicolaeChristof**
Added a lot of new assets. PLEASE TEST!!!

How to test:
- Use your earballs and make sure all the sounds are correct, I might have missed a couple because there were a lot of sounds to put in so please make sure everything is correct.

- climb to the top and make sure the squirrel doesn't clip into the new tree model (it will at the top but we are working on that)

### CODE REVIEW

**Comment by NicolaeChristof** [comment]
Thanks for the feedback. Most of the clipping stuff is not important since we are still refining our tree model. As for the acorns and mistletoe clipping, I simply didnt take the time to move every object since I knew we would be changing assets anyways. I will take a look at the unassigned references because that is a problem.

**Comment by NicolaeChristof** [comment]
the unassigned variable stuff came from me turning the tree into a prefab

**Comment by NicolaeChristof** [comment]
Take a look at dem apples ^^^

**Comment by AadamM** [comment]
> Take a look at dem apples ^^^

I think you mean take a look at dem acorns

**Comment by bdhagger** [comment]
The sap collision sound would occur three times in a row for me. It occurred most often when the squirrel touched it but it also happened when it hit the spiderweb. The sound for when I land on a branch also was a bit delayed.

**Pull request merged**
