### PR TITLE
Base Class for tickable scripts

### PR DESCRIPTION
**Pull request by malcolmriley**
Here's a simple one, based on an idea I floated during one of the last meetings.

- Implements the abstract class `RiseBehavior` for our tickable scripts.
- When `Update()` is called on itself, it checks whether or not the game is paused.
- If the game is not paused, calls `UpdateTick()`.
- Calls `UpdateAlways()` every tick regardless of whether the game is paused. `UpdateAlways()` is called before `UpdateTick()`.

Thus, if we extend `RiseBehavior` instead of `MonoBehaviour` for our game logic scripts, we can have pause sensitive logic basically for free.

The class can also be used as a place to automatically set up required references on `Start`, if there's a game object we may need to reference in multiple scripts, we can set it as a field in `RiseBehavior`, and then that field will automatically become available in every script that inherits from `RiseBehavior`.

### CODE REVIEW

**Comment by malcolmriley** [comment]
Since both `UpdateTick()` and `UpdateAlways()` are themselves abstract methods, any class that inherits from `RiseBehavior` will need to implement both.

**Comment by AadamM** [comment]
> Since both `UpdateTick()` and `UpdateAlways()` are themselves abstract methods, any class that inherits from `RiseBehavior` will need to implement both. I suppose we could change them to be virtual, so that implementors _may_ override them if they so choose.

Ah, I see. So in the current iteration I need to use "override" keywords in the function declarations, right?

**Comment by malcolmriley** [comment]
Sorry, didn't see your edit.

Unfortunately I can't seem to replicate the issue. To make `PlayerController` inherit from `RiseBehavior` and take advantage of the new methods, the following changes need to happen:

1. Class declaration should change to `public class PlayerController : RiseBehavior`
2. `Update()` method signature should be changed to `public override void UpdateTick()`
3. Implement a `public override void UpdateAlways()` method, even if it is empty.

**Comment by malcolmriley** [comment]
Addendum: If implementing empty `UpdateAlways()` methods is too inconvenient for everybody, we could simply switch it to virtual in `RiseBehavior`. I would insist that `UpdateTick()` remain abstract as a reminder as to what it's for.

**Comment by AadamM** [comment]
> Sorry, didn't see your edit.
> 
> Unfortunately I can't seem to replicate the issue. To make `PlayerController` inherit from `RiseBehavior` and take advantage of the new methods, the following changes need to happen:
> 
> 1. Class declaration should change to `public class PlayerController : RiseBehavior`
> 2. `Update()` method signature should be changed to `public override void UpdateTick()`
> 3. Implement a `public override void UpdateAlways()` method, even if it is empty.

OK, I see. I've got that in my current code but it's throwing the errors. Maybe it's just on my local machine, since you couldn't recreate the errors.

**Comment by malcolmriley** [comment]
I am baffled. No idea why you're getting ambiguity errors, there aren't any fields in `RiseBehavior`, also have no idea why those fields are getting lost. Maybe a semicolon got dropped somehow or something?

**Comment by AadamM** [comment]
> I am baffled. No idea why you're getting ambiguity errors, there aren't any fields in `RiseBehavior`, also have no idea why those fields in `PlayerController` are getting lost. Maybe a semicolon got dropped somehow or something?

Yeah, I'm not exactly sure. Maybe it's the difference between Mac line endings and Windows line endings. I fixed it by declaring _realToVirtual ratio in Start() instead of declaring it where most of the other vars are declared, but the other errors persist.

**Comment by malcolmriley** [comment]
I doubt it's the line endings, but you could try `Edit > Select All`, then `Edit > Format > Format Selection`. That should change all the line endings to your native type.

**Pull request merged**
