### PR TITLE
Squish Bugs

### PR DESCRIPTION
**Pull request by malcolmriley**
Fixes a number of bugs, cleans up a bit of code, and introduces a couple convenience tweaks.

**BUGFIXES**
- Fixes errant input bug wherein resuming play from the pause menu causes unintended inputs to be registered. **Cause:** There are quite a few scripts listening for inputs now, meaning that order of execution needs to be observed. `UIController` was executing and unpausing the game before either `TreeController` or `PlayerController` were executing, causing those scripts to respond as if the game was already unpaused. **Fix:** Set script execution order in Project Settings.
- Fixes camera bug wherein the camera track was displayed after Restart was selected from the menu. **Cause:** `UIController` was setting the camera depth incorrectly. **Fix:** Don't use depth to "disable" cameras. This doesn't actually disable them, it's like sweeping dirt under the rug. The camera continues to render, simply "underneath" the other two. In certain circumstances there would be three separate cameras rendering the same scene three times, each overlaid onto the other. This may have been a partial contributor to the performance problems. I have implemented `CameraPauseHandler` to manage pause-sensitive camera enabling.
- Fixes bug we didn't even know we had wherein `CameraControllerCentered` would fail to acquire the transform of its intended look target. **Cause:** The script relies on the fact that `Start()` would be called on `TreeController` before `CameraControllerCentered`. It is by pure coincidence that this ever worked... **Fix:** Set script execution order in Project Settings, but `CameraControllerCentered` probably needs a revisit eventually anyways. I don't think it's a good idea to do string comparisons to confirm object self-identity, this is quite brittle to change (If, for instance, we change the name of the camera, the script breaks).
- Fixes invocation failure in `FallingNutBehavior`. **Cause:** Method name was not capitalized correctly. **Fix:** Capitalize it correctly.
- Fixes NPE in UI on in-game restart. **Cause:** Seems like Unity is doing a bit of fibbing when it comes to `Start()`... seems like it's not _always_ called when a scene is reloaded. For the few render ticks before the references were reestablished, the UI scripts were peeking at the old references (of the destroyed objects). **Fix:** For now, a simple null check. For later, find out why Unity is lying to us about cleaning its room and revisit accordingly.
- Fixes incorrect reticle-squirrel follow distance. **Cause:** Existing code was using axis actuation for distance calculation and not accounting for delta time or move speed. **Fix:** Check player and reticle positions using ideal move delta (axis actuation times delta time times vertical move speed).

**ENHANCEMENTS**
- `Master Controller` is now its own fully-qualified prefab. About time! And probably about time for the Squirrel and cameras to be, too...
- `InputHelper` now has a `GetAny` method. Use this if you don't care whether the input was an axis or a button, just that it is currently activated by the player. Possibly useful if the triggers are ever revisited as an input mechanism.
- Tree reticle object is always updated, even if a move was not performed. This is a temporary measure until we can figure out why Unity doesn't clean up properly on scene reload - if `Start()` and `Awake()` aren't called reliably, how are we supposed to do init?

**CLEANUPS**
- Deleted `Fonts.meta`. Again. Who keeps committing this?
- Disable old `CameraController` scripts. They don't do anything that `CameraControllerCentered` wasn't overwriting.
- Adjust `TreeController` start position. Please don't put random `transform.Translate` calls in `Start()`, just move the damn thing in the Inspector, that's what it's for.
- Removed many pointless mode checks. The `InputHelper` handles these.

### CODE REVIEW

**Comment by malcolmriley** [comment]
**Changes since last review:**
- Re-enable standard `CameraController` script
- Squirrel is now prefab

**Comment by bdhagger** [comment]
Thanks for writing out the causes and fixes for all the issues! I also got the same bug as Aadam where the reticle stopped being able to move up when the squirrel was above it.

**Comment by malcolmriley** [comment]
**CHANGES:**
- Implemented some new convenience methods into the `InputHelper`.
- Fixed reticle vertical move bug
- Fixed event/delegate NPE on scene restart

**InputHelper Changes**
- `GetAxisRaw()` method family - Like `Input.GetAxisRaw()` from ordinary Unity. With this addition, `InputHelper` is at feature parity with Unity's `Input`.
- `GetAxisDown()` method family - Like `GetButtonDown`, but works for axes. With this addition, `InputHelper` is at feature superset of Unity's `Input`.
- `GetAnyDown()` method family - Like `GetButtonDown`, but works for axes and buttons interchangeably.
- `GetPreviousInput()` method family - This allows polling of the input actuation value on the previous tick. This can be used to detect "sharper" or "softer" actuations over time - if the value changes rapidly, the stick was probably slammed for instance.

**Reticle Vertical Move Bug Fix**
- Added the third (missing) condition to the vertical reticle movement checking and improved the code comments. Movement of the reticle is permitted under the following three circumstances:
- If the reticle move delta doesn't move it out of range of the squirrel, movement is permitted
- If the squirrel is above the reticle and the move delta is upward, movement is permitted regardless of range
- If the squirrel is below the reticle and the move delta is downward, movement is permitted regardless of range
- The previous two conditions allow the reticle to "catch up" to the squirrel's position if it is out of range (as will be necessary for the "warping" feature) but does not allow the reticle to move away from the squirrel.

**Delegate NPE on Restart Bug**
- This was a weird one.
- Using the `+=` operator to assign a delegate to an event field on another class doesn't replace any existing delegate methods; C# is the language of side-effects so what actually happens in the background is the new delegate is added to an internal list, and all delegates will be called in order when the event is invoked.
- Unity uses black magic to preserve `static` fields when object instances are disposed.
- Thus, on first launch, when `UIController` attached the delegate method to `TreeController.sapUpdated`, the delegate was appended to the empty list of delegates and all is well. When the scene was restarted, since the `sapUpdated` field was `static`, any existing delegates in the event list _weren't disposed_. Therefore, when the event was invoked, old delegates were hanging around calling null references (since the references in the actual `UpdateSapBar` method were to objects that _had_ been disposed before scene reset).
- **Fix:** Make `TreeController.sapUpdated` _not_ `static` and add a `public TreeController` field to `UIController`; this field is assigned in the Inspector. When the scene is reset, the `TreeController` is also reset fully, and no stale delegates or events will loiter around to cause problems. Curfew is in effect.

**Comment by malcolmriley** [comment]
Oh, hm. I thought I'd fixed that. I guess I got this confused with my other PR.

**Comment by malcolmriley** [comment]
Fixed, I believe.

**Comment by bdhagger** [comment]
Also, portals weren't functioning anymore, but I'm not sure if your changes are the reason for that.

**Comment by malcolmriley** [comment]
I'd like to click the big green button on this because I think the remaining UI issues will mostly be addressed by the UI changes in #129. Thoughts?

**Pull request merged**
