### PR TITLE
InputHelper Implementation

### PR DESCRIPTION
**Pull request by malcolmriley**
Implements the `InputHelper` script non-destructively: That is, without messing with existing systems. Consider this the evaluation version for the `InputHelper`, to see whether we like the way it's set up.

**Here's how it works:**
- The `InputHelper` maintains two `ControlProfile` objects, one for each possible player.
- Each `ControlProfile` maintains two `Dictionary` objects, one each for the Squirrel and Tree controls.
- These `Dictionary` objects are keyed to one of two `Enum` types: `SquirrelInput` and `TreeInput`. They return `string` that are used to query Unity's built-in `Input` methods.
- Thus, these `ControlProfile` objects are fully remappable via the `RegisterBinding` method. Yes, this means runtime rebinding of player inputs, just like Evie wanted.
- To rebind a `ControlProfile`, access either or both of `PlayerOne` or `PlayerTwo` via the `InputHelper`, and then call `RegisterBinding(input, binding)` where `input` is either a `SquirrelInput` or a `TreeInput` type, and `binding` is a `string[]` consisting of the Input Manager keys for each player and each supported controller type. Because the `string[]` would otherwise be a nightmare to manage, simply supply one of the convenience `string[]` fields in `InputHelper` - they're named after the corresponding controller mappings generically.
- This also means that two player can have two different mappings for the same roles at the same time, and swap between roles freely while maintaining their individual bindings.
- The `InputHelper` automatically manages whether the game is single-player or multi-player, and which player is playing which role.
- Thus, without worrying  about the details, we can simply query the `InputHelper` to see whether the Squirrel or Tree did something this tick.

**So how do we use them?**
- To test for a particular input, simply call any of the public methods of `InputHelper`. There are a few noteworthy ones: `GetAxis`, `GetButtonDown`, `GetButtonUp`, `GetButton`. These work identically to their counterparts in Unity's `Input` class, however you pass them either `SquirrelInput` or `TreeInput` to test for inputs for that particular role.
- There are also `Swap` and `Pause`, which are used to detect swap and pause inputs.

**Examples:**
- To check whether the squirrel player pressed the jump button, whatever that may be: `inputHelperReference.GetButtonDown(SquirrelInput.JUMP)` ... And that's it! The `InputHelper` will automatically determine whether the game is single or multiplayer, which gamepad to query for the input, and what the input is bound to in the first place.
- To rebind player one's tree pause key to the X button, do `inputHelperReference.PlayerOne.RegisterBinding(TreeInput.PAUSE, inputHelperReference.X)`. As before, `InputHelper` will automatically manage the minutia.

**Important:** Note that because `InputHelper` is not static, you will need a reference to it in order to call any of its methods. This allows the `InputHelper` to be initialized lazily. For ideas on how to access it properly, see [my comment here](https://github.com/NicolaeChristof/Rise/pull/96#issuecomment-464425445).

**PLEASE NOTE:**
- This is only the implementation of the `InputHelper`, and _not_ integration with existing systems. I have created this PR so that the `InputHelper` can be tested without interfering with other systems for now.
- If this PR is accepted, I will create a new one for using the `InputHelper` with the rest of our code.
- I also added Xbox 360 bindings to the Input Manager as a bonus, so users should be able to use a 360 controller or a One controller, but on the Windows Universal Platform _only_, because...
- Guess what! Unity considers the following input devices to all be mutually different: Xbox 360 controller on Windows, Xbox One controller on Windows, Xbox 360 controller on OSX, Xbox One controller on OSX, Xbox 360 controller on Linux, Xbox One controller on Linux. This means that all the bindings are higgledy piggledy and I might have screwed some of them up. _**PLEASE TEST BEFORE APPROVING**_

**To test the features of this PR:** Plug in one (or two) controllers, play around with the single-multiplayer booleans in `GameModel` and watch the Unity console. I have set it to print inputs as they are entered. If anything is broken, let me know.

### CODE REVIEW

**Comment by malcolmriley** [comment]
Thanks, I knew I goofed on something. I decided about halfway through integration to do that in a different PR, looks like I forgot to revert my change in the Input Manager; I've updated `GameModel` to use the correct key string.

There's potentially four ways we can access `InputHelper.` It's not a static class so we can't just call it directly, so we can instead:
1. Add a public field pointing to the Master Controller object, and fetch the `InputHelper` object from it as you suggested
2. In `Start()` on the scripts we need input access, Do `GameObject.Find` and then `GetComponent<InputHelper>()`, storing the result in a `_input` field for later use
3. Implement #97 and do the previous in `RiseBehavior`, giving us input access everywhere
4. Go through the paces of making `InputHelper` static, though this would mean we'd need to be more careful about how we initialize and call it.

**Comment by malcolmriley** [comment]
Updated header comment for clarity.

**Comment by NicolaeChristof** [comment]
Everything looks great! Also as a side not I figured out why I thought branch deletion wasn't working earlier. It works fine on keyboard but it seems that LT on controller doesn't delete a branch. Might wanna take a look at that.

If you would like to add the integration with our existing systems into this PR we could see how it all fits together :)

**Comment by malcolmriley** [comment]
`LT` isn't working for you either? I thought I was going insane! I figured it had to be some kind of input mangling by my OS or drivers or something and just crossed my fingers that it would work for others. Duodecuple checked the binding in the input manager and everything. Either way, the issue isn't with `InputHelper`, since it doesn't mess with existing systems at all in this PR.

Anyways the reason I'm not including integration with this PR is so that we can see whether we like the new `InputHelper` ... before we try to use it.

**Pull request merged**
