### PR TITLE
Feature new sounds

### PR DESCRIPTION
**Pull request by NicolaeChristof**
All our sounds are up to date with the sounds in the drive as of yesterday.

sound is fully 3d so things that are far away are quiet and get louder as the player gets closer. The audio listener is now attached to the squirrel instead of the squirrel camera to aid with more realistic 3d sound placement.

Updating sounds in the future for the current obstacles in the game will be much simpler since the infrastructure is now set up

### CODE REVIEW

**Comment by NicolaeChristof** [comment]
Do you want me to completely remove the falling sound and only have the collision sound? I could turn down the volume of the falling sound so it would be less noticeable.

**Comment by bdhagger** [comment]
Reducing the volume and distance would be better. I still liked hearing the nuts when they were farther away so that sounds like a good solution.

**Comment by NicolaeChristof** [comment]
changing the sound of the footsteps will have to be done in the original waveform to avoid me doing weird things in code. The footsteps are not being called in the same way as the rest of the sounds and if I were to change the volume of the footsteps the volume of every other sound coming out of that audio source would change as well.

**Comment by bdhagger** [comment]
Could you take out the footsteps in the meantime while we're waiting for new footstep sounds? For now we should use "sfx_SquirrelJump_3" for jumping, "sfx_BranchRustle" when the squirrel lands on a branch, "sfx_BranchBreak_1" for deleting a branch, "sfx_SapSlurp" for collecting sap, and "sfx_AcornImpact_1" for when a nut hits the player or a branch on the screen.

**Comment by bdhagger** [comment]
Sounds much better!

**Comment by NicolaeChristof** [comment]
@AadamM The branch deletion sound is probably not playing because the branch is getting deleted before it has a chance to play. I will fix this later

**Pull request merged**
